INSERT INTO tb_user (name, email, password, img_Url) VALUES ('Alex', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/47.jpg');
INSERT INTO tb_user (name, email, password, img_Url) VALUES ('Maria', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://i.pinimg.com/originals/76/ef/b7/76efb7c94755748d695d3d46cf11d08d.jpg');
INSERT INTO tb_user (name, email, password, img_Url) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/62.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('John Doe', 'john.doe@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/55.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Jane Smith', 'jane.smith@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/female/2.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Michael Johnson', 'michael.johnson@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/29.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Emily Davis', 'emily.davis@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/female/18.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Robert Wilson', 'robert.wilson@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/21.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Olivia Martinez', 'olivia.martinez@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/female/55.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('William Anderson', 'william.anderson@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/38.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Sophia Thomas', 'sophia.thomas@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/female/44.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('David Jackson', 'david.jackson@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/45.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Emma White', 'emma.white@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/female/65.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Daniel Harris', 'daniel.harris@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/73.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Mia Clark', 'mia.clark@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/female/9.jpg');
INSERT INTO tb_user (name, email, password, img_url) VALUES ('Frank Joe', 'frank.joe@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/53.jpg');

INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (5, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (6, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (7, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (8, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (9, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (10, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (11, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (12, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (13, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (14, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (15, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (16, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (16, 2);

INSERT INTO tb_group (name) VALUES ('Development');
INSERT INTO tb_group (name) VALUES ('Testing');
INSERT INTO tb_group (name) VALUES ('Design');
INSERT INTO tb_group (name) VALUES ('Marketing');
INSERT INTO tb_group (name) VALUES ('Operations');
INSERT INTO tb_group (name) VALUES ('Sales');

INSERT INTO tb_group_user (group_id, user_id) VALUES (1,2);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1,3);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1,4);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1,5);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1,6);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1,13);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1,14);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2,1);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2,7);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2,15);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2,16);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3,8);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3,9);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3,10);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3,11);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3,12);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1, 7);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1, 8);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1, 9);
INSERT INTO tb_group_user (group_id, user_id) VALUES (1, 10);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2, 2);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2, 3);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2, 4);
INSERT INTO tb_group_user (group_id, user_id) VALUES (2, 5);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3, 13);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3, 14);
INSERT INTO tb_group_user (group_id, user_id) VALUES (3, 15);

INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Home page development', 'Develop the programming of home page', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T22:09:00', 1, 2);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('CRUD page development', 'Develop the programming of CRUD page', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T15:30:00', 1, 4);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Create Database', 'Create the database in SQL', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T17:12:45', 2, 5);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Send final project to client', 'After all done, send the project to client', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T22:30:12', 0, 2);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Create the documentation', 'Create the documentation of the project', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T09:10:22', 0, 3);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Debug home page code', 'Test and debug home page code', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T12:20:00', 0, 1);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Home page Design', 'Create the home page design and layout', TIMESTAMP WITHOUT TIME ZONE '2023-06-11T21:20:00', 1, 8);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('CRUD page Design', 'Create the CRUD page design and layout', TIMESTAMP WITHOUT TIME ZONE '2023-06-11T21:09:00', 1, 9);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Database optimization', 'Optimize the database performance', TIMESTAMP WITHOUT TIME ZONE '2023-06-15T14:00:00', 1, 7);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Implement user authentication', 'Implement user authentication system', TIMESTAMP WITHOUT TIME ZONE '2023-06-16T09:00:00', 1, 9);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Design logo and branding', 'Create a logo and branding elements', TIMESTAMP WITHOUT TIME ZONE '2023-06-17T10:00:00', 0, 6);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Create user documentation', 'Write user documentation for the application', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T13:00:00', 1, 8);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Implement data encryption', 'Implement data encryption for sensitive information', TIMESTAMP WITHOUT TIME ZONE '2023-06-19T09:00:00', 1, 10);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Implement payment gateway integration', 'Integrate payment gateway for online transactions', TIMESTAMP WITHOUT TIME ZONE '2023-06-22T14:00:00', 1, 3);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Perform system testing', 'Conduct comprehensive testing of the entire system', TIMESTAMP WITHOUT TIME ZONE '2023-06-23T09:00:00', 1, 7);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Create user interface wireframes', 'Design wireframes for the user interface', TIMESTAMP WITHOUT TIME ZONE '2023-06-24T10:00:00', 0, 6);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Implement data backup mechanism', 'Set up automated data backup for the system', TIMESTAMP WITHOUT TIME ZONE '2023-06-25T09:00:00', 1, 10);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Conduct user acceptance testing', 'Involve users to test the system for acceptance', TIMESTAMP WITHOUT TIME ZONE '2023-06-26T10:00:00', 1, 9);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Database migration', 'Migrate the existing database to a new server', TIMESTAMP WITHOUT TIME ZONE '2023-06-20T09:00:00', 1, 7);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Implement search functionality', 'Add search feature to the application', TIMESTAMP WITHOUT TIME ZONE '2023-06-21T14:30:00', 1, 9);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Perform load testing', 'Test the application performance under heavy load', TIMESTAMP WITHOUT TIME ZONE '2023-06-22T10:00:00', 1, 7);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Create user registration page', 'Design and develop user registration functionality', TIMESTAMP WITHOUT TIME ZONE '2023-06-23T09:00:00', 1, 9);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Optimize CSS code', 'Refactor and optimize the CSS codebase', TIMESTAMP WITHOUT TIME ZONE '2023-06-24T14:00:00', 1, 6);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Implement social media sharing', 'Integrate social media sharing functionality', TIMESTAMP WITHOUT TIME ZONE '2023-06-25T10:00:00', 1, 3);
INSERT INTO tb_task (title, description, start_Date, status, creator_id) VALUES ('Perform security audit', 'Conduct a security audit of the application', TIMESTAMP WITHOUT TIME ZONE '2023-06-26T09:00:00', 1, 7);

INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I will create the HTML for this page', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T22:11:00', 3, 1);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Ok, so I will do the CSS styling', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T22:22:00', 2, 1);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('When you finish your steps, I will take a look', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T23:01:12', 4, 1);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('We have 3 days to finish this task', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T23:12:10', 5, 1);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I think we should prioritize this task', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T22:43:15', 6, 2);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Let''s schedule a meeting to discuss the project', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T23:30:50', 7, 2);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I have some ideas for the home page design', TIMESTAMP WITHOUT TIME ZONE '2023-06-12T23:55:21', 8, 7);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('We need to fix the bug on the CRUD page', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T09:15:37', 9, 7);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The deadline for this task is approaching', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T10:28:06', 10, 3);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I will review the documentation before submission', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T11:49:58', 11, 3);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Please check the updated home page code', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T13:02:12', 12, 6);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Let''s meet tomorrow to discuss the project progress', TIMESTAMP WITHOUT TIME ZONE '2023-06-13T15:20:30', 13, 4);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I have some ideas for the database optimization', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T09:45:00', 7, 8);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Let''s discuss the implementation details in the meeting', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T10:30:00', 9, 8);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('We need to finalize the logo design by next week', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T11:15:00', 6, 9);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I will start working on the user documentation', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T12:00:00', 8, 10);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Let''s schedule a code review session for the encryption implementation', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T13:30:00', 10, 11);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Let''s research the available payment gateways for integration', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T09:45:00', 3, 12);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('We should plan for both positive and negative testing scenarios', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T10:30:00', 7, 13);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The wireframes should follow a user-friendly design approach', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T11:15:00', 6, 14);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The backup mechanism should be scheduled for daily backups', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T12:00:00', 10, 15);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('Let''s involve a diverse group of users for better testing coverage', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T13:30:00', 9, 16);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I have completed the database migration successfully', TIMESTAMP WITHOUT TIME ZONE '2023-06-20T09:15:00', 7, 17);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The search functionality is now implemented and working', TIMESTAMP WITHOUT TIME ZONE '2023-06-21T15:00:00', 9, 18);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The application performed well under heavy load during testing', TIMESTAMP WITHOUT TIME ZONE '2023-06-22T11:30:00', 7, 19);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The user registration page design is finalized', TIMESTAMP WITHOUT TIME ZONE '2023-06-23T10:15:00', 9, 20);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('I have refactored the CSS code for improved performance', TIMESTAMP WITHOUT TIME ZONE '2023-06-24T14:30:00', 6, 21);
INSERT INTO tb_comment (text, date_Time, author_id, task_id) VALUES ('The social media sharing feature is now integrated', TIMESTAMP WITHOUT TIME ZONE '2023-06-25T11:00:00', 3, 22);

INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T09:12:44', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T10:29:56');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T12:02:01', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T15:13:20');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T16:10:01', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T18:05:10');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 2, TIMESTAMP WITHOUT TIME ZONE '2023-06-16T12:11:21', TIMESTAMP WITHOUT TIME ZONE '2023-06-16T13:05:10');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (3, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T10:01:12', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T11:29:09');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (3, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T12:09:25', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T14:12:40');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (4, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T11:12:11', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T12:16:20');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (5, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T15:55:12', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T16:45:10');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (1, 6, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T22:09:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T22:29:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (8, 7, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T22:09:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T22:29:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (9, 7, TIMESTAMP WITHOUT TIME ZONE '2023-06-14T22:09:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-14T22:49:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (6, 2, TIMESTAMP WITHOUT TIME ZONE '2023-06-16T09:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-16T11:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (7, 2, TIMESTAMP WITHOUT TIME ZONE '2023-06-16T13:20:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-16T15:45:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (8, 7, TIMESTAMP WITHOUT TIME ZONE '2023-06-17T10:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-17T12:30:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (9, 7, TIMESTAMP WITHOUT TIME ZONE '2023-06-17T14:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-17T16:45:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 3, TIMESTAMP WITHOUT TIME ZONE '2023-06-18T09:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T11:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 3, TIMESTAMP WITHOUT TIME ZONE '2023-06-18T12:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T14:30:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (12, 6, TIMESTAMP WITHOUT TIME ZONE '2023-06-18T15:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-18T16:45:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (13, 4, TIMESTAMP WITHOUT TIME ZONE '2023-06-19T10:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-19T12:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (14, 1, TIMESTAMP WITHOUT TIME ZONE '2023-06-19T13:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-19T16:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (7, 8, TIMESTAMP WITHOUT TIME ZONE '2023-06-19T10:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-19T12:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (9, 8, TIMESTAMP WITHOUT TIME ZONE '2023-06-19T13:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-19T16:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (6, 9, TIMESTAMP WITHOUT TIME ZONE '2023-06-20T09:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-20T11:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (8, 10, TIMESTAMP WITHOUT TIME ZONE '2023-06-20T12:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-20T14:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (10, 11, TIMESTAMP WITHOUT TIME ZONE '2023-06-21T09:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-21T10:45:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 12, TIMESTAMP WITHOUT TIME ZONE '2023-06-26T10:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-26T12:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 13, TIMESTAMP WITHOUT TIME ZONE '2023-06-27T09:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-27T11:15:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (6, 14, TIMESTAMP WITHOUT TIME ZONE '2023-06-28T12:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-28T14:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (10, 15, TIMESTAMP WITHOUT TIME ZONE '2023-06-29T11:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-29T13:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (9, 16, TIMESTAMP WITHOUT TIME ZONE '2023-06-30T13:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-30T15:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (2, 17, TIMESTAMP WITHOUT TIME ZONE '2023-06-30T09:30:00', TIMESTAMP WITHOUT TIME ZONE '2023-06-30T11:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (3, 18, TIMESTAMP WITHOUT TIME ZONE '2023-07-01T10:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-07-01T12:00:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (4, 19, TIMESTAMP WITHOUT TIME ZONE '2023-07-02T13:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-07-02T15:30:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (5, 20, TIMESTAMP WITHOUT TIME ZONE '2023-07-03T09:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-07-03T11:30:00');
INSERT INTO tb_work (employee_id, task_id, date_Time_Start, date_Time_End) VALUES (6, 21, TIMESTAMP WITHOUT TIME ZONE '2023-07-04T14:00:00', TIMESTAMP WITHOUT TIME ZONE '2023-07-04T16:00:00');

INSERT INTO tb_task_followers (task_id, follower_id) VALUES (1,3);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (1,4);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (1,5);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (1,6);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (1,13);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (1,14);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (2,2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (2,5);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (3,3);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (3,6);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (3,2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (2,4);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (2,7);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (2,9);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (3,8);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (3,10);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (4,11);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (4,12);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (5,13);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (6,14);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (7,5);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (8, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (8, 3);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (9, 7);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (10, 9);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (11, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (11, 10);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (11, 11);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (11, 12);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (12, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (12, 9);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (12, 10);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (13, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (13, 8);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (14, 6);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (14, 9);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (15, 10);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (16, 9);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (16, 11);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (20, 1);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (20, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (18, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (18, 3);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (19, 2);
INSERT INTO tb_task_followers (task_id, follower_id) VALUES (19, 3);
